# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wcISg41Av-Ov-VsHwOq1kC5jlJDuzvmV
"""

pip install pandas

pip install geopy

pip install googlemaps

import pandas as pd
from geopy.geocoders import GoogleV3
import geopy.distance
import googlemaps

API='AIzaSyAIa1OTrteGnIzKiQcsKfjCsWmV7i_BsxI'

#geolocator = GoogleV3(api_key=API)
print(type(geolocator))

#name='Oceanside, San Diego County'
#location=geolocator.geocode(name)
#print(location.address)
#print(location.latitude,location.longitude)

file = '6000.xlsx'
df = pd.read_excel(file)
locations = df['Location']

location_dict = {'location':[], 'latitude':[], 'longitude':[]}
for location in locations:
    # 如果地址不为空
    if not pd.isna(location) and location[0] != ' ':
        res = geolocator.geocode(location)
        location_dict['location'].append(res.address)
        location_dict['latitude'].append(res.latitude)
        location_dict['longitude'].append(res.longitude)
# 将数据保存为excel
save_df  = pd.DataFrame(location_dict)
save_df.to_excel("result.xlsx", index=False)